### ISSUE TITLE
Stuck Modifier Key

### ISSUE THREAD

**Issue by duckyb** [zmkfirmware/zmk#1449]
I have been experiencing stuck modifier keys both before and after the most recent merge about this kind of issue. (I can't find the exact PR at the moment, sorry).

Keymap: https://github.com/duckyb/zmk-sweep

## So far I've found that:
+ The issue appears only when my zmk device is paired wirelessly to my PC
+ The issue appears casually, even when the keyboard is not in use
+ Pressing LCTL does not fix it, but pressing RCTL does
As a workaround I am using this macro:
```
unstick: unstick {
	label = "ZM_unstick";
	compatible = "zmk,behavior-macro";
	#binding-cells = <0>;
	bindings = <&kp LSHIFT &kp RSHIFT &kp LCTRL &kp RCTRL &kp LALT &kp RALT &kp LGUI &kp RGUI>;
};
```
+ The stuck key is either RCTL, RGUI or both

## Logs

I was able to encounter the issue during USB Logging.

I was away from my PC, and when I came back I started working on something and I pressed `LCTL + Z` to undo an action and noticed it wasn't working. Then I realized that the modifiers were stuck.

https://pastebin.com/8fix8zFV

Looking back at the log and replacing keycode hex names with human-readable names I find that I:
1) Searched "spotify" on google
2) Pressed arrow down twice to select the autocomplete entry
3) Typed "dire straits" in the search bar
`End @ line 718; [04:26:20.801,544] <dbg> zmk: hid_listener_keycode_released: usage_page 0x07 keycode 0x16 implicit_mods 0x00 explicit_mods 0x00`

All of these steps worked correctly. Then:

4) I see a `Z` keypress which is the first undo action that I tried to do but failed.
`@ line 741. [04:28:17.843,536] <dbg> zmk: hid_listener_keycode_pressed: usage_page 0x07 keycode 0x1D implicit_mods 0x01 explicit_mods 0x00`

So, between lines `718-741` something happened that messed with the modifier key. I recall trying to undo the action by first holding the `EXT` layer key, then pressing `&kp LC(Z)`.

## Log snippet

I'm pasting lines 718 to 741 here for reference (timestamps omitted):
```yaml
hid_listener_keycode_released: usage_page 0x07 keycode 0x16 implicit_mods 0x00 explicit_mods 0x00
zmk_hid_implicit_modifiers_release: Modifiers set to 0x00
zmk_endpoints_send_report: usage page 0x07
destination_connection: Address pointer 0x20009cd3
vddh_sample_fetch: ADC raw 1353 ~ 4950 mV => 100%
vddh_sample_fetch: ADC raw 1351 ~ 4945 mV => 100%
kscan_direct_read: Sending event at 0,15 state on
zmk_kscan_process_msgq: Row: 0, col: 15, position: 30, pressed: true
position_state_changed_listener: 30 bubble (no undecided hold_tap active)
position_state_down: combo: capturing position event 30
zmk_event_manager_handle_from: Listener captured the event
kscan_direct_read: Sending event at 0,10 state on
zmk_kscan_process_msgq: Row: 0, col: 10, position: 20, pressed: true
position_state_changed_listener: 20 bubble (no undecided hold_tap active)
position_state_down: combo: capturing position event 20
release_pressed_keys: combo: releasing position event 30
zmk_keymap_apply_position_state: layer: 0 position: 30, binding name: MO
mo_keymap_binding_pressed: position 30 layer 2
set_layer_state: layer_changed: layer 2 state 1
release_pressed_keys: combo: reraising position event 20
position_state_changed_listener: 20 bubble (no undecided hold_tap active)
zmk_keymap_apply_position_state: layer: 2 position: 20, binding name: KEY_PRESS
on_keymap_binding_pressed: position 20 keycode 0x107001D
hid_listener_keycode_pressed: usage_page 0x07 keycode 0x1D implicit_mods 0x01 explicit_mods 0x00
```
