### ISSUE TITLE
Keys in combos and mod-tap getting stuck

### ISSUE THREAD

**Issue by jreiter** [zmkfirmware/zmk#686]
Board: nice!nano
Shield: QAZ
User repo: https://github.com/jreiter/zmk-config/tree/qaz

The firmware I was using at the time that I most recently reproduced this was built using Github actions here: https://github.com/jreiter/zmk-config/actions/runs/578609025

Sometimes when I'm typing on my QAZ with nice!nano using ZMK, I've noticed some keys get stuck.  So far, I've only seen this happen with keys that are involved in a combo or mod-tap - primarily shift (mod-tap in my keymap) and tab (combo in my keymap).  It's pretty easy for me to reproduce by doing typing tests, so it seems to primarily happen while typing as fast as possible (about 90-100 wpm for me).  Once the key is stuck, the only way I've been able to figure out to get my board working again is to get to bootloader and reflash.

tio logs attached from the last time I made this happen, when tab got stuck.
[tio.log](https://github.com/zmkfirmware/zmk/files/6005385/tio.log)

**Comment by mcrosson** [comment]
I'm seeing similar if using combos/hold-tap sequences in quick succession. it's not consistent as i don't type too fast with the below setup but it happens just enough where it's likely the same bug for me as the original reporters

keymap / implementation in use:

https://git.kemonine.info/kemonine/keyboard/src/branch/master/zmk-config/config/artsey_v0_7.dtsi

https://git.kemonine.info/kemonine/keyboard/src/branch/master/zmk-config/config/boards/shields/corne_artsey_left

**Comment by jreiter** [comment]
Some more info that I realized was relevant after discord discussion - when tab (combo) got stuck, I was unable to make any other key presses register.  When shift (mod-tap) got stuck, I was still able to use my reset mapping.

**Comment by okke-formsma** [comment]
Thanks for the report!

Unfortunately I can't locate the TAB keypress (code 0x2B, position 37 or 39) in the logs.

Could you increase the `LOG_BUFFER_SIZE` kconfig parameter to 32000 or something like that to prevent missing logs? Also, I've made a ZMK branch that adds additional logging to combos. Could you try to reproduce with that? (https://github.com/okke-formsma/zmk/tree/combos-logging). To do this, change west.yml in your config directory as follows:

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: okke
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk
      remote: okke
      revision: combos-logging
      import: app/west.yml
  self:
    path: config
```
